/*

  Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

  1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

  By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.

*/

// generate fibonacci sequence

function fibonacci(num){
  var a = 1, b = 1, temp, evenSum = 0;

  while (a <= num){
    temp = a + b;
    b = a;
    a = temp;
    // if the number is even, add to evenSum
    if (a % 2 === 0) {
      evenSum += a; 
    }
  }
// print evenSum
console.log(evenSum);
}

fibonacci(4000000);
